import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/component/navbar/navbar";

export const metadata: Metadata = {
  title: "Signup form ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}</body>
    </html>
  );
}
